// Read this file first when adding/changing German GUI strings.
// Purpose: German (de) localization dictionary for the GUI surface.
// Scope: data only; lookup logic and the English dict live in Localization.cs (partial class Loc).

using System.Collections.Generic;

static partial class Loc
{
    static readonly Dictionary<string, string> De = new Dictionary<string, string>
    {
        { "smoke.ready", "Bereit" },
        { "common.install", "Installieren" },
        { "common.update", "Aktualisieren" },
        { "common.uninstall", "Deinstallieren" },
        { "common.refresh", "Aktualisieren" },
        { "common.clear", "Leeren" },
        { "common.remove", "Entfernen" },
        { "common.add", "Hinzufügen" },
        { "common.cancel", "Abbrechen" },
        { "common.ok", "Verstanden" },

        { "fatal.message", "AI Agent Secure ist mit einem unbehandelten Fehler beendet worden.\n\n{0}" },
        { "fatal.title", "AI Agent Secure Fehler" },
        { "tray.show", "Anzeigen" },
        { "tray.about", "Über" },
        { "tray.exit", "Beenden" },

        { "nav.dashboard", "Dashboard" },
        { "nav.folders", "Geschützte Bereiche" },
        { "nav.settings", "Einstellungen" },
        { "nav.log", "Protokoll" },
        { "nav.about", "Über" },
        { "sidebar.install", "\u2B07 Installieren" },
        { "sidebar.installed", "\u2714 Installiert" },
        { "sidebar.update", "\u21BB Aktualisieren" },
        { "sidebar.uninstall", "\u2716 Deinstallieren" },

        { "dashboard.title", "Dashboard" },
        { "dashboard.subtitle", "Übersicht deines Schutzes" },
        { "dashboard.update.title", "Aktualisierung verfügbar" },
        { "dashboard.update.hint", "Diese GUI bringt neuere Schutz-Layer mit als deine Installation. Klicke \"Jetzt aktualisieren\", um sie aktiv zu ziehen — deine Konfiguration und Whitelist bleiben erhalten." },
        { "dashboard.update.button", "Jetzt aktualisieren" },
        { "dashboard.stat.dirs", "Geschützte Bereiche" },
        { "dashboard.stat.whitelist", "Ausnahmen" },
        { "dashboard.stat.blocked", "Blockiert" },
        { "dashboard.banner.not_installed", "Schutz ist nicht installiert" },
        { "dashboard.banner.full", "Vollschutz ist aktiv" },
        { "dashboard.banner.partial", "Schutz ist teilweise aktiv" },
        { "dashboard.banner.repair", "Schutz braucht Reparatur" },
        { "dashboard.banner.disabled", "Schutz ist ausgeschaltet!" },
        { "dashboard.status.not_installed", "Nicht installiert" },
        { "dashboard.status.not_installed_hint", "Klicke links auf \"Installieren\" um den Schutz einzurichten" },
        { "dashboard.status.on", "Schutz ist AN" },
        { "dashboard.status.full_hint", "Interaktive und nicht-interaktive Bash-Sessions sind gegen gefährliche Löschbefehle geschützt" },
        { "dashboard.status.partial_hint", "Interaktive Shells sind vorbereitet. Für Vollschutz bitte BASH_ENV setzen oder Shells neu laden." },
        { "dashboard.status.repair_title", "Schutz unvollständig" },
        { "dashboard.status.repair_hint", "Die Konfiguration ist aktiv, aber weder .bashrc noch BASH_ENV sind korrekt gesetzt." },
        { "dashboard.status.off", "Schutz ist AUS" },
        { "dashboard.status.off_hint", "Deine Bereiche sind nicht geschützt!" },

        { "folders.title", "Geschützte Bereiche" },
        { "folders.subtitle", "Diese Bereiche können Ordner, Projekte oder ganze Laufwerke sein" },
        { "folders.add", "\U0001F4C1  Bereich hinzufügen" },
        { "folders.empty.title", "Noch keine Bereiche geschützt" },
        { "folders.empty.hint", "Klicke oben rechts auf \"Bereich hinzufügen\" um loszulegen" },

        { "settings.title", "Einstellungen" },
        { "settings.subtitle", "Schutz und Systemoptionen anpassen" },
        { "settings.language.title", "Sprache" },
        { "settings.language.hint", "Wechselt GUI-Text und Benachrichtigungen zwischen Englisch und Deutsch. Shell-Blockmeldungen bleiben agentensicher Englisch/ASCII." },
        { "settings.language.en", "English" },
        { "settings.language.de", "Deutsch" },
        { "action.change_language", "Sprache umschalten" },
        { "settings.categories.title", "Schutz-Kategorien" },
        { "settings.categories.hint", "Einzelne Schutzarten unabhängig steuern. Der Master-Schalter auf dem Dashboard deaktiviert immer alles auf einmal." },
        { "settings.delete.title", "Lösch-Schutz" },
        { "settings.delete.hint", "Blockiert 'rm -rf', 'cmd rmdir /s' und PowerShell 'Remove-Item -Recurse' in geschützten Bereichen." },
        { "settings.git.title", "Git-Schutz" },
        { "settings.git.hint", "Blockiert 'git stash' auf einem dirty Worktree (verhindert verlorene Arbeit durch Agents, die stashen und nie poppen)." },
        { "settings.git_leak.title", "Git-Leak-Schutz" },
        { "settings.git_leak.hint", "Warnt bevor 'git push' wahrscheinliche Secrets oder Agent-Arbeitsdateien veröffentlicht. Unbeantwortete Prompts blockieren automatisch." },
        { "settings.leak_timeout.title", "Leak-Allow-Timeout (Sekunden)" },
        { "settings.leak_timeout.hint", "Wie lange der Terminal-Prompt auf 'allow' wartet, bevor der Push blockiert wird. Default: 60 Sekunden." },
        { "settings.corruption.title", "Git-Korruptions-Schutz" },
        { "settings.corruption.hint", "Blockiert Byte-Korruption - CRCRLF-Zeilenenden und verbotene Steuerzeichen (01-08, 0B, 0C, 0E-1F, 7F) - bei 'git add', 'git commit' (staged, -a, --include, --only) und im ausgehenden Bereich vor 'git push'." },
        { "settings.empty_file.title", "Leere-/Null-Datei-Schutz" },
        { "settings.empty_file.hint", "Blockiert inhaltsleere Dateien - 0 Byte und reine Nullbytes (jedes Byte 0x00) - beim Eintritt in Git via 'git add', 'git commit' und im ausgehenden Bereich vor 'git push'. Das ist die Truncation-/Crash-Korruption, die der Byte-Scanner überspringt." },
        { "settings.git_flood.title", "Git Flood-Schutz" },
        { "settings.git_flood.hint", "Bremst durchdrehende Agents: blockiert nach zu vielen Netzwerk-git-Aufrufen (push/pull/fetch) im Zeitfenster." },
        { "settings.flood_threshold.title", "Flood-Schwellwert" },
        { "settings.flood_threshold.hint", "Maximale Anzahl Netzwerk-git-Aufrufe pro Zeitfenster, bevor blockiert wird." },
        { "settings.flood_window.title", "Flood-Zeitfenster (Sekunden)" },
        { "settings.flood_window.hint", "Zeitraum, in dem die Aufrufe gezählt werden. Default: 60 Sekunden." },
        { "settings.http_api.title", "HTTP/API-Schutz" },
        { "settings.http_api.hint", "Blockiert authentifizierte curl-Aufrufe, die wie destruktive API-Löschungen aussehen, z.B. DELETE oder delete-Mutationen." },
        { "settings.ps_utf8.title", "PowerShell-UTF-8-Pflicht" },
        { "settings.ps_utf8.hint", "Blockiert PowerShell-Schreibvorgänge ohne explizites UTF-8-Encoding und verhindert UTF-16-BOM- sowie CP1252/ANSI-Korruption von Quellcode-Dateien." },
        { "settings.details.toggle", "Schutzdetails anzeigen" },
        { "settings.details.blocked", "Blockiert" },
        { "settings.details.allowed", "Erlaubt" },
        { "settings.details.delete.blocked.rm", "rm -rf in geschützten Bereichen" },
        { "settings.details.delete.blocked.cmd", "cmd /c rmdir /s /q in geschützten Bereichen" },
        { "settings.details.delete.blocked.ps", "PowerShell Remove-Item -Recurse in geschützten Bereichen" },
        { "settings.details.delete.blocked.cwd", "rmdir /s mit unklarem Ziel, wenn das aktuelle Verzeichnis geschützt ist" },
        { "settings.details.delete.allowed.files", "Einzelne Dateien und nicht-rekursive Löschbefehle" },
        { "settings.details.delete.allowed.safe", "Erlaubte Ausnahmen wie node_modules, dist, build oder .cache" },
        { "settings.details.delete.allowed.outside", "Löschen außerhalb geschützter Bereiche" },
        { "settings.details.git.blocked.stash_dirty", "git stash / push / save, wenn der Worktree Änderungen enthält" },
        { "settings.details.git.blocked.stash_mutation", "git stash pop, apply, drop, clear, store und andere Stash-Mutationen" },
        { "settings.details.git.blocked.reset", "git reset --hard, wenn tracked Änderungen verloren gingen" },
        { "settings.details.git.blocked.clean", "git clean -f, wenn wirklich Dateien entfernt würden" },
        { "settings.details.git.blocked.overwrite", "checkout, switch oder restore Formen, die lokale Änderungen überschreiben würden" },
        { "settings.details.git.blocked.branch", "git branch -D, wenn der Branch noch ungemergte Commits enthält" },
        { "settings.details.git.allowed.stash_read", "git stash list, show, create und help" },
        { "settings.details.git.allowed.clean_dry", "git clean Dry-Runs und interaktives clean" },
        { "settings.details.git.allowed.clean_tree", "Saubere Worktrees und No-op-Kommandos" },
        { "settings.details.git.allowed.reset_soft", "git reset --soft, --mixed und pfadbezogene reset Formen" },
        { "settings.details.git_leak.blocked.env", ".env, .env.*, versehentliche .emv-Dateien und Auth-Dotfiles wie .npmrc" },
        { "settings.details.git_leak.blocked.agent", ".claude- und .codex-Arbeitsdaten sowie agent.md/agend.md" },
        { "settings.details.git_leak.blocked.credentials", "Private Keys, Service-Account-JSON, credentials.*, secrets.* und config.php-Varianten" },
        { "settings.details.git_leak.blocked.timeout", "Keine Terminal-Antwort, 'ignore' oder Timeout nach den konfigurierten Sekunden" },
        { "settings.details.git_leak.allowed.examples", ".env.example, .env.local.example und Templates wie config.example.php" },
        { "settings.details.git_leak.allowed.clean_push", "Pushes, deren ausgehende Commits keine verdächtigen Dateipfade enthalten" },
        { "settings.details.git_leak.allowed.force", "Geprüfter einmaliger Agent-Bypass über SHELL_SECURE_GIT_LEAK_FORCE=1" },
        { "settings.details.corruption.blocked.add", "git add, wenn ausgewählte Worktree-Dateien CRCRLF oder verbotene Steuerzeichen enthalten" },
        { "settings.details.corruption.blocked.commit", "git commit, wenn gestagte Blobs CRCRLF oder verbotene Steuerzeichen enthalten" },
        { "settings.details.corruption.blocked.commit_all", "git commit -a, wenn tracked Änderungen CRCRLF oder Steuerzeichen enthalten" },
        { "settings.details.corruption.blocked.commit_pathspec", "git commit --only/Pathspec, wenn ausgewählte tracked Dateien CRCRLF oder Steuerzeichen enthalten" },
        { "settings.details.corruption.blocked.push", "git push, wenn der ausgehende Commit-Bereich CRCRLF oder Steuerzeichen enthält (bereits committete Korruption)" },
        { "settings.details.empty_file.blocked.new", "git add/commit einer NEUEN leeren oder reinen-Null-Datei mit Pflichtinhalt-Endung (.php/.js/.ts/.json/.css/.html/.sql/...)" },
        { "settings.details.empty_file.blocked.truncate", "git add/commit einer getrackten Datei, die Inhalt hatte und jetzt 0 Byte oder reine Nullbytes ist (Truncation)" },
        { "settings.details.empty_file.blocked.push", "git push, wenn der ausgehende Bereich einen leeren/genullten Blob enthält, der vorher Inhalt hatte" },
        { "settings.details.corruption.allowed.clean", "Dateien mit reinen Text-Bytes (TAB, LF, CR; LF- oder CRLF-Zeilenenden)" },
        { "settings.details.corruption.allowed.existing", "Historische add/commit-Schulden außerhalb der aktuellen Operation (Hinweis: der Pre-Push-Scan meldet committete Korruption im ausgehenden Bereich)" },
        { "settings.details.corruption.allowed.force", "Geprüfte manuelle Freigabe: einmalig SHELL_SECURE_CORRUPTION_FORCE=1, oder persistente Inhalts-SHA256-Allowlist in ~/.shell-secure/corruption-allowlist (verifizierte vendored Bytes; schärft bei jeder Byte-Änderung neu)" },
        { "settings.details.empty_file.allowed.legit", "Eingebaute gewollte Leerdateien: .gitkeep, .keep, __init__.py, py.typed, .nojekyll, gc.properties, sowie temp/- und logs/-Pfade" },
        { "settings.details.empty_file.allowed.allowlist", "Pfade oder Globs in ~/.shell-secure/empty-file-allowlist" },
        { "settings.details.empty_file.allowed.force", "Geprüfter einmaliger Bypass über SHELL_SECURE_EMPTY_FILE_FORCE=1" },
        { "settings.details.flood.blocked.network", "Wiederholte push, pull, fetch, clone oder ls-remote Aufrufe" },
        { "settings.details.flood.blocked.threshold", "Mehr Aufrufe als der konfigurierte Schwellwert im Zeitfenster" },
        { "settings.details.flood.blocked.agent_loop", "Durchlaufende Schleifen, die Remote-git dauerhaft anstoßen" },
        { "settings.details.flood.allowed.local", "Lokale git-Kommandos wie status, log, diff, branch oder commit" },
        { "settings.details.flood.allowed.under_limit", "Netzwerkaufrufe, solange sie unter dem Schwellwert bleiben" },
        { "settings.details.flood.allowed.window_reset", "Neue Aufrufe nachdem das konfigurierte Zeitfenster verstrichen ist" },
        { "settings.details.http.blocked.delete", "Authentifizierte curl -X DELETE Aufrufe" },
        { "settings.details.http.blocked.destructive_payload", "Authentifizierte POST-, PUT- oder PATCH-Aufrufe mit Aktions-/Operationsfeldern, GraphQL-Mutationen oder destruktiven API-Pfaden" },
        { "settings.details.http.blocked.authenticated", "Provider-API-Aufrufe mit Bearer Token, API-Key, Cookies, netrc oder Basic Auth" },
        { "settings.details.http.allowed.readonly", "Nur lesende curl-Aufrufe, Such-/Query-Payloads, Vorschau-Endpunkte und nicht authentifizierte API-Aufrufe" },
        { "settings.details.http.allowed.unauthenticated", "Destruktiv aussehende Beispiele ohne Zugangsdaten, z.B. für Dokumentation oder Tests" },
        { "settings.details.http.allowed.permission", "Erneutes Ausführen nach expliziter Nutzerfreigabe und Ressourcenprüfung" },
        { "settings.details.ps.blocked.cmdlets", "Set-Content/Add-Content (ANSI/CP1252) und Out-File (UTF-16-BOM) ohne -Encoding utf8" },
        { "settings.details.ps.blocked.redirect", "PowerShell-Umleitungsschreibvorgänge wie > und >> (UTF-16-BOM in Windows PowerShell 5.1)" },
        { "settings.details.ps.blocked.dotnet", ".NET-Textschreibvorgänge ohne sichtbares UTF-8-Encoding oder mit unsicheren Encodings wie Unicode, ASCII oder UTF7" },
        { "settings.details.ps.allowed.encoding", "Schreibvorgänge mit explizitem UTF-8-/65001-Encoding" },
        { "settings.details.ps.allowed.gitbash", "Schreibvorgänge direkt aus Git Bash" },
        { "settings.details.ps.allowed.readonly", "Nur lesende PowerShell-Kommandos" },
        { "settings.autostart.title", "Beim Hochfahren starten" },
        { "settings.autostart.hint", "AI Agent Secure startet automatisch mit Windows" },
        { "settings.system.title", "Systemstatus" },
        { "settings.git_bash.found", "\u2714  Git Bash: {0}" },
        { "settings.git_bash.missing", "\u2716  Git Bash nicht gefunden!" },
        { "settings.bash_env.full", "\u2714  BASH_ENV gesetzt \u2014 Bash-Sessions geschützt" },
        { "settings.bash_env.chained", "\u2714  BASH_ENV verkettet \u2014 AI Agent Secure und bestehender Loader sind aktiv" },
        { "settings.bash_env.foreign", "\u2716  BASH_ENV zeigt auf etwas anderes \u2014 AI Agent Secure greift nicht überall" },
        { "settings.bash_env.missing", "\u26A0  BASH_ENV nicht gesetzt \u2014 nur interaktive Shells geschützt" },
        { "settings.whitelist.title", "Erlaubte Ausnahmen" },
        { "settings.whitelist.hint", "Ordner mit diesen Namen dürfen trotzdem gelöscht werden (z.B. Build-Dateien)" },
        { "settings.whitelist.add", "+ Hinzufügen" },

        { "log.title", "Protokoll" },
        { "log.subtitle", "Alle blockierten Operationen" },
        { "log.empty.title", "Keine Bedrohungen blockiert" },
        { "log.empty.hint", "Alles in Ordnung!" },

        { "about.title", "Über AI Agent Secure" },
        { "about.subtitle", "Release- und Projektinformationen" },
        { "about.core", "Schutz-Core: {0}" },
        { "about.version", "Version: {0}" },
        { "about.build", "Build: {0}" },
        { "about.commit", "Commit: {0}" },
        { "about.built", "Gebaut: {0} UTC" },
        { "about.author", "Autor: {0}" },
        { "about.project", "Projekt: {0}" },

        { "action.toggle_delete", "Lösch-Schutz umschalten" },
        { "action.toggle_git", "Git-Schutz umschalten" },
        { "action.toggle_git_flood", "Git Flood-Schutz umschalten" },
        { "action.toggle_git_leak", "Git-Leak-Schutz umschalten" },
        { "action.toggle_corruption", "Git-Korruptions-Schutz umschalten" },
        { "action.toggle_empty_file", "Leere-/Null-Datei-Schutz umschalten" },
        { "action.change_leak_timeout", "Git-Leak-Allow-Timeout ändern" },
        { "action.change_flood_threshold", "Flood-Schwellwert ändern" },
        { "action.change_flood_window", "Flood-Zeitfenster ändern" },
        { "action.toggle_http_api", "HTTP/API-Schutz umschalten" },
        { "action.toggle_ps_utf8", "PowerShell-UTF-8-Pflicht umschalten" },
        { "action.add_folder", "Bereich hinzufügen" },
        { "action.remove_exception", "Ausnahme entfernen" },
        { "action.clear_log", "Protokoll leeren" },
        { "dialog.folder_picker", "Ordner oder Laufwerk auswählen, das geschützt werden soll:" },
        { "dialog.remove_dir.message", "Schutz für diesen Bereich entfernen?\n\n{0}\n\nDer Pfad selbst wird NICHT gelöscht." },
        { "dialog.remove_dir.title", "Schutz entfernen" },
        { "dialog.add_exception.title", "Ausnahme hinzufügen" },
        { "dialog.add_exception.prompt", "Welcher Ordnername soll trotzdem gelöscht werden dürfen?\n\nBeispiele: .mypy_cache, .sass-cache, obj" },
        { "dialog.clear_log.message", "Protokoll wirklich leeren?" },
        { "dialog.clear_log.title", "Protokoll leeren" },
        { "dialog.git_bash_missing.message", "Git Bash wurde nicht gefunden.\n\nAI Agent Secure braucht Git Bash und bricht die Installation deshalb ab." },
        { "dialog.git_bash_missing.title", "Git Bash fehlt" },
        { "dialog.uninstall.message", "AI Agent Secure wirklich komplett entfernen?" },
        { "dialog.uninstall.title", "Deinstallieren" },
        { "dialog.save_failed", "Konfiguration konnte nicht gespeichert werden." },
        { "config.load_failed", "Konfiguration konnte nicht geladen werden: {0}" },
        { "config.not_installed", "AI Agent Secure ist noch nicht installiert." },
        { "config.save_failed", "Konfiguration konnte nicht gespeichert werden: {0}" },
        { "dialog.install_required.title", "Installation erforderlich" },
        { "dialog.install_required.message", "AI Agent Secure ist noch nicht installiert.\n\nBitte zuerst installieren, bevor du \"{0}\" verwendest." },

        { "toast.multi", "Mehrere Aktionen blockiert" },
        { "toast.git_flood", "Git-Flood blockiert" },
        { "toast.git_leak", "Git-Leak blockiert" },
        { "toast.git_corruption", "Git-Korruption blockiert" },
        { "toast.empty_file", "Leere/genullte Datei blockiert" },
        { "toast.write_corruption", "Schreib-Korruption blockiert" },
        { "toast.http_api", "HTTP-API-Aufruf blockiert" },
        { "toast.ps_utf8", "PowerShell-Schreibvorgang blockiert" },
        { "toast.git", "Git-Aktion blockiert" },
        { "toast.delete", "Löschversuch blockiert" },
        { "toast.details", "Klicken für Details im Protokoll." },
        { "toast.one_prevented", "Ein Versuch wurde verhindert." },
        { "toast.many_prevented", "{0} Versuche wurden verhindert." },

        { "installer.error_prefix", "Fehler: {0}" },
        { "installer.git_bash_missing", "Fehler: Git Bash wurde nicht gefunden. Installation abgebrochen." },
        { "installer.protection_installed", "Schutz-Modul installiert" },
        { "installer.default_config_created", "Standard-Einstellungen erstellt" },
        { "installer.existing_config_kept", "Bestehende Einstellungen beibehalten" },
        { "installer.shell_config_updated", "Shell-Konfiguration aktualisiert" },
        { "installer.bash_env_correct", "BASH_ENV ist bereits korrekt gesetzt" },
        { "installer.bash_env_enabled", "BASH_ENV für nicht-interaktive Bash-Shells aktiviert" },
        { "installer.bash_env_chained", "BASH_ENV wurde mit bestehendem Loader verkettet" },
        { "installer.shortcut_created", "Startmenü-Verknüpfung erstellt (für Windows-Benachrichtigungen)" },
        { "installer.shortcut_warning", "Warnung: Startmenü-Verknüpfung konnte nicht erstellt werden ({0})" },
        { "installer.install_done", "\nFertig! Der Schutz ist jetzt aktiv." },
        { "installer.log_backup", "Protokoll gesichert: {0}" },
        { "installer.removed", "Schutz wurde komplett entfernt." },
        { "installer.install_first", "Bitte zuerst installieren." },
        { "installer.updated", "Schutz-Modul wurde aktualisiert." }
    };
}
