// Read this file first when adding/changing localizable GUI strings.
// Purpose: key-based localization for the GUI surface.
// Scope: covers GUI text only. Bash runtime block diagnostics stay
//        English/ASCII in lib/protection-i18n.sh for agent-safe output.

using System;
using System.Collections.Generic;

static partial class Loc
{
    // Active language code. Defaults to "en"; flipped to "de" by Init()
    // when the parsed config explicitly requests German. Anything else
    // resolves to English so future locales fail safely instead of
    // silently dropping back to half-localised state.
    public static string Lang = "en";

    public static void Init(string raw)
    {
        Lang = string.Equals(raw, "de", StringComparison.OrdinalIgnoreCase) ? "de" : "en";
    }

    static readonly Dictionary<string, string> En = new Dictionary<string, string>
    {
        { "smoke.ready", "Ready" },
        { "common.install", "Install" },
        { "common.update", "Update" },
        { "common.uninstall", "Uninstall" },
        { "common.refresh", "Refresh" },
        { "common.clear", "Clear" },
        { "common.remove", "Remove" },
        { "common.add", "Add" },
        { "common.cancel", "Cancel" },
        { "common.ok", "Got it" },

        { "fatal.message", "AI Agent Secure exited because of an unhandled error.\n\n{0}" },
        { "fatal.title", "AI Agent Secure Error" },
        { "tray.show", "Show" },
        { "tray.about", "About" },
        { "tray.exit", "Exit" },

        { "nav.dashboard", "Dashboard" },
        { "nav.folders", "Protected Areas" },
        { "nav.settings", "Settings" },
        { "nav.log", "Log" },
        { "nav.about", "About" },
        { "sidebar.install", "\u2B07 Install" },
        { "sidebar.installed", "\u2714 Installed" },
        { "sidebar.update", "\u21BB Update" },
        { "sidebar.uninstall", "\u2716 Uninstall" },

        { "dashboard.title", "Dashboard" },
        { "dashboard.subtitle", "Protection overview" },
        { "dashboard.update.title", "Update available" },
        { "dashboard.update.hint", "This GUI contains newer protection layers than your installation. Click \"Update now\" to activate them. Your configuration and whitelist stay intact." },
        { "dashboard.update.button", "Update now" },
        { "dashboard.stat.dirs", "Protected areas" },
        { "dashboard.stat.whitelist", "Exceptions" },
        { "dashboard.stat.blocked", "Blocked" },
        { "dashboard.banner.not_installed", "Protection is not installed" },
        { "dashboard.banner.full", "Full protection is active" },
        { "dashboard.banner.partial", "Protection is partially active" },
        { "dashboard.banner.repair", "Protection needs repair" },
        { "dashboard.banner.disabled", "Protection is off!" },
        { "dashboard.status.not_installed", "Not installed" },
        { "dashboard.status.not_installed_hint", "Click \"Install\" on the left to set up protection" },
        { "dashboard.status.on", "Protection is ON" },
        { "dashboard.status.full_hint", "Interactive and non-interactive Bash sessions are protected against dangerous delete commands" },
        { "dashboard.status.partial_hint", "Interactive shells are prepared. For full protection, set BASH_ENV or reload your shells." },
        { "dashboard.status.repair_title", "Protection incomplete" },
        { "dashboard.status.repair_hint", "The configuration is active, but neither .bashrc nor BASH_ENV is set correctly." },
        { "dashboard.status.off", "Protection is OFF" },
        { "dashboard.status.off_hint", "Your areas are not protected!" },

        { "folders.title", "Protected Areas" },
        { "folders.subtitle", "These areas can be folders, projects, or entire drives" },
        { "folders.add", "\U0001F4C1  Add area" },
        { "folders.empty.title", "No areas protected yet" },
        { "folders.empty.hint", "Click \"Add area\" in the top right to get started" },

        { "settings.title", "Settings" },
        { "settings.subtitle", "Adjust protection and system options" },
        { "settings.language.title", "Language" },
        { "settings.language.hint", "Switches GUI text and notifications between English and German. Shell block diagnostics stay English/ASCII for agent-safe output." },
        { "settings.language.en", "English" },
        { "settings.language.de", "Deutsch" },
        { "action.change_language", "change language" },
        { "settings.categories.title", "Protection Categories" },
        { "settings.categories.hint", "Control individual protection types independently. The master switch on the dashboard always disables everything at once." },
        { "settings.delete.title", "Delete Protection" },
        { "settings.delete.hint", "Blocks 'rm -rf', 'cmd rmdir /s', and PowerShell 'Remove-Item -Recurse' inside protected areas." },
        { "settings.git.title", "Git Protection" },
        { "settings.git.hint", "Blocks 'git stash' on a dirty worktree, preventing lost work from agents that stash and never pop." },
        { "settings.git_leak.title", "Git Leak Protection" },
        { "settings.git_leak.hint", "Warns before 'git push' publishes likely secrets or agent workspace files. Unanswered prompts block automatically." },
        { "settings.leak_timeout.title", "Leak allow timeout (seconds)" },
        { "settings.leak_timeout.hint", "How long the terminal prompt waits for 'allow' before blocking the push. Default: 60 seconds." },
        { "settings.corruption.title", "Git Corruption Protection" },
        { "settings.corruption.hint", "Blocks byte-level corruption - CRCRLF line endings and forbidden control bytes (01-08, 0B, 0C, 0E-1F, 7F) - on 'git add', 'git commit' (staged, -a, --include, --only), and the outgoing range before 'git push'." },
        { "settings.empty_file.title", "Empty / Zeroed File Protection" },
        { "settings.empty_file.hint", "Blocks content-free files - 0-byte and all-NUL (every byte 0x00) - from entering Git on 'git add', 'git commit', and the outgoing range before 'git push'. This is the truncation/crash corruption the byte scanner skips." },
        { "settings.git_flood.title", "Git Flood Protection" },
        { "settings.git_flood.hint", "Slows runaway agents by blocking after too many network git calls (push/pull/fetch) in the time window." },
        { "settings.flood_threshold.title", "Flood threshold" },
        { "settings.flood_threshold.hint", "Maximum number of network git calls per time window before blocking." },
        { "settings.flood_window.title", "Flood time window (seconds)" },
        { "settings.flood_window.hint", "Time span in which calls are counted. Default: 60 seconds." },
        { "settings.http_api.title", "HTTP/API Protection" },
        { "settings.http_api.hint", "Blocks authenticated curl calls that look like destructive API deletes, such as DELETE or delete mutations." },
        { "settings.ps_utf8.title", "Require PowerShell UTF-8" },
        { "settings.ps_utf8.hint", "Blocks PowerShell writes without explicit UTF-8 encoding, preventing UTF-16 BOM and CP1252/ANSI corruption in source files." },
        { "settings.details.toggle", "Show protection details" },
        { "settings.details.blocked", "Blocked" },
        { "settings.details.allowed", "Allowed" },
        { "settings.details.delete.blocked.rm", "rm -rf inside protected areas" },
        { "settings.details.delete.blocked.cmd", "cmd /c rmdir /s /q inside protected areas" },
        { "settings.details.delete.blocked.ps", "PowerShell Remove-Item -Recurse inside protected areas" },
        { "settings.details.delete.blocked.cwd", "rmdir /s with an unclear target while the current directory is protected" },
        { "settings.details.delete.allowed.files", "Single-file deletes and non-recursive deletes" },
        { "settings.details.delete.allowed.safe", "Allowed exception names such as node_modules, dist, build, or .cache" },
        { "settings.details.delete.allowed.outside", "Deletes outside protected areas" },
        { "settings.details.git.blocked.stash_dirty", "git stash / push / save when the worktree contains changes" },
        { "settings.details.git.blocked.stash_mutation", "git stash pop, apply, drop, clear, store, and other stash mutations" },
        { "settings.details.git.blocked.reset", "git reset --hard when tracked changes would be lost" },
        { "settings.details.git.blocked.clean", "git clean -f when files would actually be removed" },
        { "settings.details.git.blocked.overwrite", "checkout, switch, or restore forms that would overwrite local changes" },
        { "settings.details.git.blocked.branch", "git branch -D when the branch still has unmerged commits" },
        { "settings.details.git.allowed.stash_read", "git stash list, show, create, and help" },
        { "settings.details.git.allowed.clean_dry", "git clean dry-runs and interactive clean" },
        { "settings.details.git.allowed.clean_tree", "Clean worktrees and no-op commands" },
        { "settings.details.git.allowed.reset_soft", "git reset --soft, --mixed, and path-limited reset forms" },
        { "settings.details.git_leak.blocked.env", ".env, .env.*, accidental .emv files, and auth dotfiles such as .npmrc" },
        { "settings.details.git_leak.blocked.agent", ".claude and .codex workspace data plus agent.md/agend.md" },
        { "settings.details.git_leak.blocked.credentials", "Private keys, service-account JSON, credentials.*, secrets.*, and config.php variants" },
        { "settings.details.git_leak.blocked.timeout", "No terminal answer, 'ignore', or timeout after the configured seconds" },
        { "settings.details.git_leak.allowed.examples", ".env.example, .env.local.example, and config.example.php style templates" },
        { "settings.details.git_leak.allowed.clean_push", "Pushes where the outgoing commits contain no suspicious file paths" },
        { "settings.details.git_leak.allowed.force", "Reviewed one-shot agent bypass via SHELL_SECURE_GIT_LEAK_FORCE=1" },
        { "settings.details.corruption.blocked.add", "git add when selected worktree files contain CRCRLF or forbidden control bytes" },
        { "settings.details.corruption.blocked.commit", "git commit when staged blobs contain CRCRLF or forbidden control bytes" },
        { "settings.details.corruption.blocked.commit_all", "git commit -a when tracked modified files contain CRCRLF or control bytes" },
        { "settings.details.corruption.blocked.commit_pathspec", "git commit --only/pathspec when selected tracked files contain CRCRLF or control bytes" },
        { "settings.details.corruption.blocked.push", "git push when the outgoing commit range contains CRCRLF or control bytes (already-committed corruption)" },
        { "settings.details.empty_file.blocked.new", "git add/commit of a NEW empty or all-NUL file with a content-mandatory extension (.php/.js/.ts/.json/.css/.html/.sql/...)" },
        { "settings.details.empty_file.blocked.truncate", "git add/commit of a tracked file that had content but is now 0-byte or all-NUL (truncation)" },
        { "settings.details.empty_file.blocked.push", "git push when the outgoing range contains an empty/zeroed blob that previously had content" },
        { "settings.details.corruption.allowed.clean", "Files with only normal text bytes (TAB, LF, CR; LF or CRLF endings)" },
        { "settings.details.corruption.allowed.existing", "Historical add/commit debt outside the current operation (note: the pre-push scan does flag committed corruption in the outgoing range)" },
        { "settings.details.corruption.allowed.force", "Reviewed manual release: one-shot SHELL_SECURE_CORRUPTION_FORCE=1, or a persistent content-SHA256 allowlist in ~/.shell-secure/corruption-allowlist (verified vendored bytes; re-arms on any byte change)" },
        { "settings.details.empty_file.allowed.legit", "Built-in intentional empties: .gitkeep, .keep, __init__.py, py.typed, .nojekyll, gc.properties, plus temp/ and logs/ paths" },
        { "settings.details.empty_file.allowed.allowlist", "Paths or globs listed in ~/.shell-secure/empty-file-allowlist" },
        { "settings.details.empty_file.allowed.force", "Reviewed one-shot bypass via SHELL_SECURE_EMPTY_FILE_FORCE=1" },
        { "settings.details.flood.blocked.network", "Repeated push, pull, fetch, clone, or ls-remote calls" },
        { "settings.details.flood.blocked.threshold", "More calls than the configured threshold within the time window" },
        { "settings.details.flood.blocked.agent_loop", "Runaway loops that keep hitting remote git operations" },
        { "settings.details.flood.allowed.local", "Local git commands such as status, log, diff, branch, or commit" },
        { "settings.details.flood.allowed.under_limit", "Network calls while they stay under the threshold" },
        { "settings.details.flood.allowed.window_reset", "New calls after the configured time window has passed" },
        { "settings.details.http.blocked.delete", "Authenticated curl -X DELETE requests" },
        { "settings.details.http.blocked.destructive_payload", "Authenticated POST, PUT, or PATCH requests with action/operation fields, GraphQL mutations, or destructive API paths" },
        { "settings.details.http.blocked.authenticated", "Provider API calls carrying bearer tokens, API keys, cookies, netrc auth, or basic auth" },
        { "settings.details.http.allowed.readonly", "Read-only curl requests, search/query payloads, preview endpoints, and unauthenticated API calls" },
        { "settings.details.http.allowed.unauthenticated", "Destructive-looking examples without credentials, useful for docs or tests" },
        { "settings.details.http.allowed.permission", "Re-running after explicit user permission and resource verification" },
        { "settings.details.ps.blocked.cmdlets", "Set-Content/Add-Content (ANSI/CP1252) and Out-File (UTF-16 BOM) without -Encoding utf8" },
        { "settings.details.ps.blocked.redirect", "PowerShell redirection writes such as > and >> (UTF-16 BOM in Windows PowerShell 5.1)" },
        { "settings.details.ps.blocked.dotnet", ".NET text writes without visible UTF-8 encoding, or with unsafe encodings such as Unicode, ASCII, or UTF7" },
        { "settings.details.ps.allowed.encoding", "Writes with explicit UTF-8 / 65001 encoding" },
        { "settings.details.ps.allowed.gitbash", "Writes performed directly from Git Bash" },
        { "settings.details.ps.allowed.readonly", "Read-only PowerShell commands" },
        { "settings.autostart.title", "Start with Windows" },
        { "settings.autostart.hint", "AI Agent Secure starts automatically with Windows" },
        { "settings.system.title", "System status" },
        { "settings.git_bash.found", "\u2714  Git Bash: {0}" },
        { "settings.git_bash.missing", "\u2716  Git Bash not found!" },
        { "settings.bash_env.full", "\u2714  BASH_ENV set - Bash sessions protected" },
        { "settings.bash_env.chained", "\u2714  BASH_ENV chained - AI Agent Secure and the existing loader are active" },
        { "settings.bash_env.foreign", "\u2716  BASH_ENV points somewhere else - AI Agent Secure is not active everywhere" },
        { "settings.bash_env.missing", "\u26A0  BASH_ENV not set - only interactive shells are protected" },
        { "settings.whitelist.title", "Allowed Exceptions" },
        { "settings.whitelist.hint", "Folders with these names may still be deleted, for example build artifacts" },
        { "settings.whitelist.add", "+ Add" },

        { "log.title", "Log" },
        { "log.subtitle", "All blocked operations" },
        { "log.empty.title", "No threats blocked" },
        { "log.empty.hint", "Everything looks good!" },

        { "about.title", "About AI Agent Secure" },
        { "about.subtitle", "Release and project information" },
        { "about.core", "Protection core: {0}" },
        { "about.version", "Version: {0}" },
        { "about.build", "Build: {0}" },
        { "about.commit", "Commit: {0}" },
        { "about.built", "Built: {0} UTC" },
        { "about.author", "Author: {0}" },
        { "about.project", "Project: {0}" },

        { "action.toggle_delete", "toggle Delete Protection" },
        { "action.toggle_git", "toggle Git Protection" },
        { "action.toggle_git_flood", "toggle Git Flood Protection" },
        { "action.toggle_git_leak", "toggle Git Leak Protection" },
        { "action.toggle_corruption", "toggle Git Corruption Protection" },
        { "action.toggle_empty_file", "toggle Empty / Zeroed File Protection" },
        { "action.change_leak_timeout", "change Git Leak allow timeout" },
        { "action.change_flood_threshold", "change flood threshold" },
        { "action.change_flood_window", "change flood time window" },
        { "action.toggle_http_api", "toggle HTTP/API Protection" },
        { "action.toggle_ps_utf8", "toggle PowerShell UTF-8 requirement" },
        { "action.add_folder", "add area" },
        { "action.remove_exception", "remove exception" },
        { "action.clear_log", "clear log" },
        { "dialog.folder_picker", "Select the folder or drive to protect:" },
        { "dialog.remove_dir.message", "Remove protection for this area?\n\n{0}\n\nThe path itself will NOT be deleted." },
        { "dialog.remove_dir.title", "Remove protection" },
        { "dialog.add_exception.title", "Add exception" },
        { "dialog.add_exception.prompt", "Which folder name may still be deleted?\n\nExamples: .mypy_cache, .sass-cache, obj" },
        { "dialog.clear_log.message", "Really clear the log?" },
        { "dialog.clear_log.title", "Clear log" },
        { "dialog.git_bash_missing.message", "Git Bash was not found.\n\nAI Agent Secure needs Git Bash, so installation is cancelled." },
        { "dialog.git_bash_missing.title", "Git Bash missing" },
        { "dialog.uninstall.message", "Really remove AI Agent Secure completely?" },
        { "dialog.uninstall.title", "Uninstall" },
        { "dialog.save_failed", "Configuration could not be saved." },
        { "config.load_failed", "Configuration could not be loaded: {0}" },
        { "config.not_installed", "AI Agent Secure is not installed yet." },
        { "config.save_failed", "Configuration could not be saved: {0}" },
        { "dialog.install_required.title", "Installation required" },
        { "dialog.install_required.message", "AI Agent Secure is not installed yet.\n\nPlease install first before you use \"{0}\"." },

        { "toast.multi", "Multiple actions blocked" },
        { "toast.git_flood", "Git flood blocked" },
        { "toast.git_leak", "Git leak blocked" },
        { "toast.git_corruption", "Git corruption blocked" },
        { "toast.empty_file", "Empty/zeroed file blocked" },
        { "toast.write_corruption", "Write corruption blocked" },
        { "toast.http_api", "HTTP API call blocked" },
        { "toast.ps_utf8", "PowerShell write blocked" },
        { "toast.git", "Git action blocked" },
        { "toast.delete", "Delete attempt blocked" },
        { "toast.details", "Click for details in the log." },
        { "toast.one_prevented", "One attempt was prevented." },
        { "toast.many_prevented", "{0} attempts were prevented." },

        { "installer.error_prefix", "Error: {0}" },
        { "installer.git_bash_missing", "Error: Git Bash was not found. Installation cancelled." },
        { "installer.protection_installed", "Protection module installed" },
        { "installer.default_config_created", "Default settings created" },
        { "installer.existing_config_kept", "Existing settings kept" },
        { "installer.shell_config_updated", "Shell configuration updated" },
        { "installer.bash_env_correct", "BASH_ENV is already set correctly" },
        { "installer.bash_env_enabled", "BASH_ENV enabled for non-interactive Bash shells" },
        { "installer.bash_env_chained", "BASH_ENV was chained with the existing loader" },
        { "installer.shortcut_created", "Start Menu shortcut created (for Windows notifications)" },
        { "installer.shortcut_warning", "Warning: Start Menu shortcut could not be created ({0})" },
        { "installer.install_done", "\nDone! Protection is now active." },
        { "installer.log_backup", "Log saved: {0}" },
        { "installer.removed", "Protection was completely removed." },
        { "installer.install_first", "Please install first." },
        { "installer.updated", "Protection module was updated." }
    };

    // Returns the localized string for `key`. Falls back to English when
    // the active language has no entry, then to the literal key so that
    // typos surface visibly in the UI rather than being silently empty.
    public static string T(string key)
    {
        string value;
        if (Lang == "de" && De.TryGetValue(key, out value))
            return value;
        if (En.TryGetValue(key, out value))
            return value;
        return key;
    }

    public static string F(string key, params object[] args)
    {
        return string.Format(T(key), args);
    }
}
